# Generated by Django 4.2 on 2023-05-01 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=170)),
                ('ip', models.CharField(max_length=170)),
                ('user_agent', models.CharField(max_length=170)),
                ('id_user', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
